# Generated by Django 3.2 on 2020-07-26 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_text', models.CharField(max_length=200)),
                ('content_text', models.CharField(max_length=1500)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('views', models.IntegerField(default=0)),
            ],
        ),
    ]
